# Generated by Django 4.1.2 on 2022-10-23 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="interview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("topic", models.CharField(max_length=200)),
                ("researcher_id", models.CharField(max_length=100)),
                ("consent", models.TextField(blank=True, null=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("purpose", models.TextField(blank=True, null=True)),
                ("participant_id", models.TextField(blank=True, null=True)),
                ("mode", models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="participant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("photo", models.FileField(blank=True, upload_to="researcher_photo")),
                ("name", models.CharField(max_length=100)),
                ("nick_name", models.CharField(max_length=100)),
                ("Current_location", models.CharField(max_length=100)),
                ("nationality", models.CharField(max_length=100)),
                ("gender", models.CharField(max_length=50)),
                ("age", models.IntegerField()),
                ("study_field", models.CharField(max_length=100)),
                ("Email", models.CharField(max_length=100)),
                ("Password", models.CharField(max_length=100)),
                ("login", models.CharField(max_length=100)),
                ("phone_number", models.CharField(max_length=50)),
                ("social_media", models.CharField(blank=True, max_length=200)),
                ("work_experience", models.JSONField(blank=True, null=True)),
                ("education", models.JSONField(blank=True, null=True)),
                ("marital_status", models.BooleanField(default=0)),
                ("incentive", models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="researcher",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("photo", models.FileField(blank=True, upload_to="researcher_photo")),
                ("name", models.CharField(max_length=100)),
                ("nick_name", models.CharField(max_length=100)),
                ("Current_location", models.CharField(max_length=100)),
                ("nationality", models.CharField(max_length=100)),
                ("gender", models.CharField(max_length=50)),
                ("age", models.IntegerField()),
                ("study_field", models.CharField(max_length=100)),
                ("Email", models.CharField(max_length=100)),
                ("Password", models.CharField(max_length=100)),
                ("login", models.CharField(max_length=100)),
                ("phone_number", models.CharField(max_length=50)),
                ("social_media", models.CharField(blank=True, max_length=200)),
            ],
        ),
    ]
